In [ ]:
'''
What is NumPy?

It is a Python library that is frequently used in Data Science for scientic computing.
That is, it provides many useful features for performing mathematical and logical operations on n-arrays, matrices, and etc.

But, why NumPy?
  - huge difference in size of objects in memory between NumPy and Python
  - time efficient
  - very powerful when used in conjunction with other libraries
'''

In [2]:
import numpy as np
import sys

In [3]:
# Comparing between NumPy and Python

In [4]:
sys.getsizeof(1) # 28 bytes for a simple integer, such as 1, in python

28

In [5]:
np.dtype(int).itemsize # only 8 bytes in numpy

8

In [6]:
l = list(range(1000)) # python list consisting of 1000 elements
a = np.arange(1000) # numpy array consisting of 1000 elements

In [10]:
%time sum([i**2 for i in l]) # squaring each element and summing them up in python

CPU times: user 244 µs, sys: 52 µs, total: 296 µs
Wall time: 299 µs


332833500

In [11]:
%time np.sum(a**2) # squaring each element and summing them up in numpy

CPU times: user 84 µs, sys: 18 µs, total: 102 µs
Wall time: 107 µs


332833500

In [12]:
#################### Basic NumPy Arrays ########################

In [13]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [14]:
a[0], a[2], a[-1] # same indexing, as well as, slicing in numpy as in python list

(1, 3, 5)

In [15]:
a[[0, 2, -1]]

array([1, 3, 5])

In [16]:
A = np.array([
              [
               [12, 11, 10],
               [9, 8, 7]
              ],
              [
               [6, 5, 4],
               [3, 2, 1]
              ]
])
A

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [17]:
A.ndim # dimension

3

In [18]:
A.shape # 2 x 2 x 3

(2, 2, 3)

In [19]:
A.size # total count of elements

12

In [20]:
#################### Basic NumPy Matrices ########################

# same indexing and slicing concept applies to matrices

In [21]:
b = np.array([
            #  0  1  2
              [1, 2, 3], # 0
              [4, 5, 6], # 1
              [7, 8, 9]  # 2
])

In [22]:
b[1]

array([4, 5, 6])

In [23]:
b[1][0] # is equivalent to b[1, 0]

4

In [24]:
b[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
b[1] = np.array([0, 0, 0]) # manipulating the entire second row

In [26]:
b[2, 1] = 0
b

array([[1, 2, 3],
       [0, 0, 0],
       [7, 0, 9]])

In [27]:
#################### Statistical Operation ########################

In [28]:
a = np.array([1, 2, 3, 4, 5])

In [29]:
a.sum()

15

In [30]:
a.mean()

3.0

In [31]:
a.std() # a.var() for variation

1.4142135623730951

In [32]:
b = np.array([
            #  0  1  2
              [1, 2, 3], # 0
              [4, 5, 6], # 1
              [7, 8, 9]  # 2
])

In [33]:
b.sum()

45

In [34]:
b.mean()

5.0

In [35]:
b.std() # b.var() for variation

2.581988897471611

In [36]:
b.sum(axis = 0) # sum of columns

array([12, 15, 18])

In [37]:
b.sum(axis = 1) # sum of rows

array([ 6, 15, 24])

In [38]:
#################### Broadcasting and Vectorized Operations ########################

# one of fundamental pieces in numpy

In [39]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [40]:
a + 10

array([10, 11, 12, 13])

In [41]:
a * 10

array([ 0, 10, 20, 30])

In [42]:
a = np.arange(4)                #[0, 1, 2, 3]
b = np.array([10, 10, 10, 10])  #[10, 10, 10, 10]

In [43]:
a + b

array([10, 11, 12, 13])

In [44]:
a * b

array([ 0, 10, 20, 30])

In [45]:
#################### Boolean Arrays ########################

In [46]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [47]:
a >= 2

array([False, False,  True,  True])

In [48]:
a[a >= 2] # returns the only elements that satisfy the given condition

array([2, 3])

In [49]:
a[~(a > a.mean())] # a.mean() = 1.5

array([0, 1])

In [50]:
A = np.random.randint(50, size=(3,3)) # creating a 3x3 matrix by selecting each element randomly from the specified range
A

array([[18, 26, 11],
       [ 2, 30, 20],
       [26, 49,  2]])

In [51]:
A[A > 15]

array([18, 26, 30, 20, 26, 49])

In [52]:
#################### Linear Algebra ########################

In [53]:
A = np.array([
            #  0  1  2
              [1, 2, 3], # 0
              [4, 5, 6], # 1
              [7, 8, 9]  # 2
])

In [54]:
B = np.array([
              [5, 6],
              [3, 4],
              [1, 2]
])

In [55]:
A.dot(B) # Dot product ("A @ B" would return the same result as well.)

array([[14, 20],
       [41, 56],
       [68, 92]])

In [56]:
B.T # Transpose 

array([[5, 3, 1],
       [6, 4, 2]])

In [57]:
np.cross(A, B) # Cross product

array([[-18,  15,  -4],
       [-24,  18,   1],
       [-18,   9,   6]])

In [58]:
#################### Other Useful NumPy Built-in Functions ########################

In [59]:
# random
# arange
# reshape
# linspace
# zeros, ones, empty
# identity, eye